export const ErrorCodes = {
  PROJECT_NOT_FOUND: "PROJECT_NOT_FOUND",
  PROJECT_INVALID: "PROJECT_INVALID",

  PKG_MANAGER_NOT_FOUND: "PKG_MANAGER_NOT_FOUND",
  PKG_INSTALL_FAILED: "PKG_INSTALL_FAILED",

  CONFIG_PARSE_ERROR: "CONFIG_PARSE_ERROR",
  CONFIG_CONFLICT: "CONFIG_CONFLICT",

  COMMAND_NOT_FOUND: "COMMAND_NOT_FOUND",
  INVALID_ARGUMENT: "INVALID_ARGUMENT",
  USER_CANCELLED: "USER_CANCELLED",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
